Repository nurion4hep/HEP-GNN, pull requests merged in 2020-09, with the labels that each got.

#13 bugfix wrong sign to keep best weights, to not use gpu when unavailable
  run/run_train.py
Labels: bug

#14 Bugfix to work with sparse case
  run/run_eval.py
  scripts/buildGraphs.py
Labels: bug

#15 New file output
  scripts/buildGraphs.py
Labels: New feature, bug

#16 Bugfix buildgraph indexing
  scripts/buildGraphs.py
Labels: bug

#18 Update config.yaml
  run/config.yaml
Labels: New feature

#20 remove chunksize option
  scripts/buildGraphs.py
Labels: bug
